[supervisord]
nodaemon=true
user=root

[program:postgres]
command=/usr/lib/postgresql/14/bin/postgres -D /var/lib/postgresql/14/main -c config_file=/etc/postgresql/14/main/postgresql.conf
user=postgres
autorestart=true

[program:django]
command=python3 manage.py runserver 0.0.0.0:8000
directory=/app
autorestart=true