# Generated by Django 4.2.11 on 2026-01-20 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='priority',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
